#!/bin/bash
set -eo pipefail

CONTAINERNAME="nats-server"
NETWORKNAME="nats-net"

docker network create $NETWORKNAME

docker run -p 4222:4222 \
  --name $CONTAINERNAME \
  --network $NETWORKNAME \
  -v $(pwd)/jetstream:/data/jetstream \
  -v $(pwd)/nats-server.conf:/etc/nats/nats-server.conf \
  -ti nats:latest -js -c /etc/nats/nats-server.conf

# network muss wieder entfernt werden
docker network rm $NETWORKNAME

# docker container loeschen
docker remove $CONTAINERNAME  