[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-timers = "0.3.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"

[lib]
crate-type = ["cdylib"]
